use_frameworks!

platform :ios, '10.0'

target 'NHT_Network_Example' do
  pod 'NHT_Network', :path => '../'

  target 'NHT_Network_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
